apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: springtrader
    workspace: .

  - imageName: sqlfdb
    workspace: ./sqlfdb

  local: {}

deploy:
  helm:
    releases:
      - name: springtrader
        chartPath: ./charts/springtrader
        values:
          image: springtrader
          sqlfdb: sqlfdb
        setValueTemplates:
          istio.domain: "{{if .INGRESS_DOMAIN}}{{.INGRESS_DOMAIN}}{{else}}default{{end}}"
          istio.namespace: "{{if .TILLER_NAMESPACE}}{{.TILLER_NAMESPACE}}{{else}}default{{end}}"
