apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: springtrader 
    workspace: .

#  - imageName: rabbitmq
#    workspace: ./rabbitmq
  local: {}

deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        values:
          image: springtrader 
#          rabbitimage: rabbitmq
