apiVersion: apps/v1
kind: Deployment
metadata:
    name: springtrader-app 
spec:
    selector:
      matchLabels:
        app: springtrader-app 
    template:
      metadata:
        labels:
            app: springtrader-app 
      spec:
        containers:
        - name: sqlfdb
          image: {{ .Values.sqlfdb }}

        - name: springtrader
          image: {{ .Values.image }}

        - name: rabbitmq
          image: rabbitmq:latest

