apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gateway"
  namespace: "{{ .Values.istio.namespace }}"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "{{ .Chart.Name }}.{{ .Values.istio.domain }}"
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "{{ .Chart.Name }}.{{ .Values.istio.domain }}"
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: "sds"
      privateKey: "sds"
      credentialName: "{{ .Values.istio.namespace }}-certificate"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.istio.namespace }}"
spec:
  hosts:
  - "{{ .Chart.Name }}.{{ .Values.istio.domain }}"
  gateways:
  - "{{ .Chart.Name }}-gateway"
  http:
  - route:
    - destination:
        host: springtrader-app
        port:
          number: 8080
